# Generated by Django 5.0.7 on 2024-07-26 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item_model', '0001_initial'),
        ('item_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_type', models.CharField(max_length=4)),
                ('print_mass', models.DecimalField(decimal_places=2, max_digits=5)),
                ('print_time', models.TimeField()),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_model.itemmodel')),
                ('type_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_type.itemtype')),
            ],
        ),
    ]
