# Generated by Django 5.0.7 on 2024-07-30 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
        ('plastic', '0001_initial'),
        ('printer', '0002_printer_hour_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plastic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plastic.plastic')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printer.printer')),
            ],
        ),
    ]
