# Generated by Django 5.0.7 on 2024-07-31 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='print_time',
            field=models.PositiveIntegerField(),
        ),
    ]
