# Generated by Django 5.0.7 on 2024-07-28 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_model', '0001_initial'),
        ('item_type', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='model_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='item_type.itemtype'),
            preserve_default=False,
        ),
    ]
