# Generated by Django 5.0.7 on 2024-07-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_name', models.CharField(max_length=40)),
                ('printer_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('printer_resource', models.IntegerField()),
                ('print_materials_cost', models.DecimalField(decimal_places=2, max_digits=7)),
                ('printer_power', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
