# Generated by Django 5.0.7 on 2024-07-26 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item_color', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plastic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('plastic_type', models.CharField(max_length=45)),
                ('plastic_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('plastic_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_color.itemcolor')),
            ],
        ),
    ]
